### ISSUE TITLE
aws rds 연결방법

### ISSUE THREAD

**Issue by baeksoojin** [Web-For-PhotoGrapher/Our_Spring_Project#7]
## aws rds database 연결방법

1. application.yaml 
```
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://{엔드포인트}:{포트번호}/{(초기)데이터베이스}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: {마스터 사용자 이름}
        password: {마스터 암호}
```

2. 구성정보

- 엔드포인트 : 보안상 notion에 올려두겠습니다!
- 포트번호 : 3306
- 초기 데이터베이스 : photo_spot_map
- username : root
- password : 보안상 notion에 올려두겠습니다!

3. **주의**

application.yaml을 꼭 gitignore에 등록해주세요!!
